

export GOBIN=$(shell pwd)/bin

build:
	go vet     github.com/the-cloud-source/reverse/...
	go test    github.com/the-cloud-source/reverse/...
	go build   github.com/the-cloud-source/reverse/...
	go vet     github.com/the-cloud-source/reverse/cmd/...
	go test    github.com/the-cloud-source/reverse/cmd/...
	go install github.com/the-cloud-source/reverse/cmd/...
